export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SET_SNACKBAR = "SET_SNACKBAR";
export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

export const UPDATE_PROJECTS_START = "UPDATE_PROJECTS_START";
export const UPDATE_PROJECTS_SUCCESS = "UPDATE_PROJECTS_SUCCESS";
export const UPDATE_PROJECTS_FAIL = "UPDATE_PROJECTS_FAIL";

export const SET_ACTIVE_PROJECT_START = "SET_ACTIVE_PROJECT_START";
export const SET_ACTIVE_PROJECT_SUCCESS = "SET_ACTIVE_PROJECT_SUCCESS";
export const SET_ACTIVE_PROJECT_FAIL = "SET_ACTIVE_PROJECT_FAIL";
export const CLEAR_ACTIVE_PROJECT = "CLEAR_ACTIVE_PROJECT";

export const FETCH_BEACONS_START = "FETCH_BEACONS_START";
export const FETCH_BEACONS_SUCCESS = "FETCH_BEACONS_SUCCESS";
export const FETCH_BEACONS_FAIL = "FETCH_BEACONS_FAIL";

export const SET_BEACON_UID_START = "SET_BEACON_UID_START";
export const SET_BEACON_UID_SUCCESS = "SET_BEACON_UID_SUCCESS";
export const SET_BEACON_UID_FAIL = "SET_BEACON_UID_FAIL";

export const SET_ACTIVE_PROJECT_MODE = "SET_ACTIVE_PROJECT_MODE";
